[all]
master1 ansible_host=188.121.119.166 ip=192.168.0.44
worker1 ansible_host=37.32.25.51 ip=192.168.2.138

[docker_servers]
gitlab

[haproxy_servers]
lb1
lb2

[traefik_servers]
master1

[kubernetes_servers]
master1
worker1

[kube_control_plane]
master1

[etcd]
master1

[kube_nodes]
worker1

[k8s_cluster:children]
kube_control_plane
kube_nodes

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa
domain_name=anikmlm.ir
virtual_ip={{ vault_virtual_ip }}
password={{ vault_password }}


dns_servers:
  - "178.22.122.100"
  - "185.51.200.2"