[all]
lb1 ansible_host=185.204.170.20 ip=192.168.2.254
lb2 ansible_host=185.204.170.20 ip=192.168.2.254
master1 ansible_host=185.204.170.20 ip=192.168.2.254
worker1 ansible_host=185.204.170.215 ip=192.168.3.114

[docker_servers]
gitlab


[haproxy_servers]
lb1
lb2

[traefik_servers]
master1

[kubernetes_servers]
master1
worker1

[kube_masters]
master1

[etcd]
master1

[kube_nodes]
worker1

[k8s_cluster:children]
kube_masters
kube_nodes


[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa
domain_name=anikmlm.ir
virtual_ip={{ vault_virtual_ip }}
password={{ vault_password }}
